# The label to apply to this deployment, 
# used to manage multiple instances of the same application
Instance: default

# The HTML data that nginx should serve
Data: |-
  <html>
  <body>
  <h1>Hello world!</h1>
  </body>
  </html>