apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  labels:
    app: nginx
    instance: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      instance: demo
  template:
    metadata:
      labels:
        app: nginx
        instance: demo
    spec:
      containers:
      - name: nginx
        image: "nginx:1.7.9"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always