apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  labels:
    app: nginx
    instance: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      instance: demo
  template:
    metadata:
      labels:
        app: nginx
        instance: demo
    spec:
      containers:
      - name: nginx
        image: "nginx:1.7.9"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    instance: demo
  name: demo-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    instance: demo