apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-{{ .Values.Instance }}-configuration
  labels:
    app: nginx
    instance: {{ .Values.Instance }}
data:
  index.html: |-
{{ .Values.Data | indent 4 }}